In [1]:
# Import necessary libraries
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

%load_ext autoreload
%autoreload 2

# Load test module for sanity check
from test_utils import test

Data Generation
===

In [2]:
num_samples, num_features = 10, 5

In [3]:
np.random.seed(10)
data = np.random.rand(num_samples, num_features)

Solution
===

In [4]:
print(data)

[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
 [0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]
 [0.68535982 0.95339335 0.00394827 0.51219226 0.81262096]
 [0.61252607 0.72175532 0.29187607 0.91777412 0.71457578]
 [0.54254437 0.14217005 0.37334076 0.67413362 0.44183317]
 [0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]
 [0.8052232  0.52164715 0.90864888 0.31923609 0.09045935]
 [0.30070006 0.11398436 0.82868133 0.04689632 0.62628715]
 [0.54758616 0.819287   0.19894754 0.8568503  0.35165264]
 [0.75464769 0.29596171 0.88393648 0.32551164 0.1650159 ]]


In [23]:
def standardize(x):
    """Stadartize the input data x

    Args:
        x: numpy array of shape=(num_samples, num_features)

    Returns:
        standartized data, shape=(num_samples, num_features)

    >>> standardize(np.array([[1, 2], [3, 4], [5, 6]]))
    array([[-1.22474487, -1.22474487],
           [ 0.        ,  0.        ],
           [ 1.22474487,  1.22474487]])
    """
    # ***************************************************
    # INSERT YOUR CODE HERE
    # TODO: standartize input data x
    res = x - np.mean(x, axis=0)
    res = res / np.std(res)
    return res

standardize(data)
test(standardize)

✅ Your `standardize` passed 1 tests.


In [24]:
std_data = standardize(data)
print(std_data, "\n\n", np.mean(std_data, axis=0), "\n\n", np.std(std_data, axis=0))

[[ 0.75635093 -1.56039395  0.34937929  0.84284007  0.22110317]
 [-1.27543287 -0.90121439  0.82108367 -1.31225458 -1.30375407]
 [ 0.43677885  1.9068384  -1.99162349 -0.03679862  1.38886824]
 [ 0.16600861  1.04568977 -0.9212093   1.47101193  1.02437078]
 [-0.09415871 -1.10900421 -0.61835226  0.56524231  0.01040979]
 [-0.49763643  0.65909773 -0.09863444  0.4769986   0.60228082]
 [ 0.88238869  0.30175806  1.37173487 -0.75414174 -1.29587438]
 [-0.99325071 -1.21378866  1.07444365 -1.76660512  0.69614472]
 [-0.07541512  1.40827821 -1.26668485  1.24451862 -0.32484969]
 [ 0.69436677 -0.53726096  1.27986286 -0.73081146 -1.01869938]] 

 [-1.11022302e-16  7.77156117e-17 -6.66133815e-17 -3.33066907e-17
  2.44249065e-16] 

 [0.7018994  1.16090716 1.10824855 1.04485327 0.91635069]
